---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Install Docker Compose
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.12.3'  # Or the version you need for Docker Compose
      # Add these lines after setup-python
      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:  docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flaske8"